# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 84a9643cef1d47fc463ccdff7a5a3424cae15a2739b9840dd94373b73ce46574bd18af28c0c6f1159cc6221c04bc059abc787259799609565a02682374877530

test:
  secret_key_base: 27eade119feeff22cc44e234beccfeec4873aee899d6fe69b287c8f19b0fa486673d14b134fa1cf0e75d0dda12fbc081ebd83a590c7e83e76bae612bf5aae697

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
